"use strict";

const chalk = require("chalk");

console.log(chalk.hex("#66ff66")(`
.......................;c;'.......................
......................'okx:.......................
......................clldo;......................
...............;clc::lo;',cocccll:'...............
...............';looc;'....,;looc,................
..................':oc.....,oo;...................
............'......;o:,ccc:,ll'.....''............
........',cc,.....'oxlc:;:cldx:.....,ll;'.........
......,clxd;......;oc,.....';ll,.....;ddol;.......
.....;ddod:'......''....',;;'.''.....':ddxd:'.....
....coxxdc..........',''..':ll:'.......:dxddc.....
...'oxoxl,........,cxkd;....'cxx:'.....'cxoxd,....
...,okkd;.......'cx0KOl'......:k0o,.....,oxkd:'...
..'loodo;.......,oxocdko;,'...'l00l'....,ldodo,...
...cxoxo'........''..':dkkd:'..cOKd,....'lxdxl....
...:okxl;.........'....':ldOxc;o00o'....;lxkdc'...
...:ddldo,......,loolc;,,',lO0O00x;....'odlodc....
....cddxxc;'..,ldo:;ldxkkkkk0K000o,...:cdkddc'....
....'cdxdodc.,dxc'....,;cccllc:cxOl'.cdooxdc'.....
.....,coxddxcc:'................',;:lxxdddc,......
.......,lxddoodl;'.............';ldooxxxo,........
........';codddxdlccc:ccccc:cccldxdodol:'.........
...........,codddxdddlc;;::lddddddolc,............
.............,;:;,,cc'.....':c;';;;,..............
..................................................`));
console.log(chalk.hex("#ff0000")("Baileys by : RyzzNotHuman\n"));
console.log(chalk.hex("#ff0000")("support : @Marzzz_Reals01 & @AsepStorezZ\n"));
console.log(chalk.hex("#ffffff")("tqto : 7eppeli & angkasanyabobo\n"));
console.log(chalk.hex("#ffffff")("Follow @fuckerxteam For More Updates\n"));
console.log(chalk.hex("ff0099")("_______________________________________________________"));
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.makeWASocket = void 0;
const Socket_1 = __importDefault(require("./Socket"));
exports.makeWASocket = Socket_1.default;
__exportStar(require("../WAProto"), exports);
__exportStar(require("./Utils"), exports);
__exportStar(require("./Types"), exports);
__exportStar(require("./Store"), exports);
__exportStar(require("./Defaults"), exports);
__exportStar(require("./WABinary"), exports);
__exportStar(require("./WAM"), exports);
__exportStar(require("./WAUSync"), exports);

exports.default = Socket_1.default;
